Rwa 441
hmcts/wa-task-configuration-api pull request #158
Opened 2021-03-26 09:14 UTC by lewis150193

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-244

### Change description ###
Idam pact test

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2021-03-26 09:16 UTC, iguannago approved these changes

2021-03-30 07:10 UTC, BenNzewi commented on build.gradle
> +  id 'au.com.dius.pact' version '4.0.4'
Please reference the following ia-case-api branch "ConsumerContractTests". It's the most up to date PACT change for case-api.

version should be -> id 'au.com.dius.pact' version '4.1.0'

2021-03-30 07:13 UTC, BenNzewi commented on src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/CcdCasePactTest.java
> +package uk.gov.hmcts.reform.wataskconfigurationapi;
Should this be under in a CCD PACT Test class?

2021-03-30 07:13 UTC, BenNzewi commented on src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/IdamConsumerTestForPostToken.java
> +    @Pact(provider = "Idam_api", consumer = "wa_task_management_api")
It appears we are referring to an out of date implementation of case-api. I spoke to Satya and we should use the implementation on the following ia-case-api branch "ConsumerContractTests".

Please reference the following ia-case-api branch "ConsumerContractTests".
For example;
In @Pact(provider = "Idam_api", consumer = "wa_task_management_api"), Idam_api should be idamApi_oidc

2021-03-30 07:14 UTC, BenNzewi commented on src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/IdamConsumerTestForPostUserInfo.java
> +    @Pact(provider = "Idam_api", consumer = "wa_task_management_api")
Please reference the following ia-case-api branch "ConsumerContractTests".
For example;
In @Pact(provider = "Idam_api", consumer = "wa_task_management_api"), Idam_api should be idamApi_oidc

2021-03-30 09:35 UTC, indvamshi commented on src/contractTest/java/uk/gov/hmcts/reform/wataskconfigurationapi/ccdpacttest/CcdCasePactTest.java
> +                .extract().asString();
can we verify for 200 status code. Same in other scenarios as well.

2021-03-30 09:45 UTC, alexbaeza requested changes

2021-03-30 09:45 UTC, alexbaeza commented on build.gradle
> +  publish {
There's some config missing here used by the new version see this one for an example:
https://github.com/hmcts/wa-task-management-api/pull/169

2021-03-31 11:02 UTC, alexbaeza commented on build.gradle
> +  pacticipant = 'wa_taskConfigurationApi'
```suggestion
  pacticipant = 'wa_task_configuration_api'
```

2021-03-31 11:22 UTC, alexbaeza approved these changes

2021-03-31 12:17 UTC, merged